### ISSUE TITLE
-extend to respond to _arduino discovery without breaking OTA library

### ISSUE THREAD

**Issue by MikeyMoMo** [gartnl/mDNS-alternative-ESP32#1]
I see no action for the past 11 months.  Will this ever be fixed?  I would like to use mDNS and OTA on the same board.  From testing of another mDNS library, it appears to not work.  Seems you have the same problem.

Surely would like to see this fixed.  My skills don't apply here!

Thanks, Mike

**Comment by gartnl** [comment]
Don't know about the official ESP software. SInce I don't really use OTA this was a quick fix for me to get mDNS working to find devices by name on my network. But I never followed up on it to get more options. 
As far as I remember OTA is a very specific library, depending om the original mDNS library. Changing that would involve rewriting part of t he OTA library.

**Comment by MikeyMoMo** [comment]
Yeah, mDNS works and OTA works but not on the same device at the same time.  And... it won't be fixed, apparently.  So, pick one or the other.  Closing this now.
